/** Renders the scenario-coverage report as Markdown and as a console summary. */

const LAYER_LABELS = {
  backend: 'backend integration',
  frontend: 'frontend unit',
  e2e: 'end-to-end',
}

export function renderMarkdown(analysis, layers, generatedAt) {
  const lines = []

  lines.push('# Scenario coverage')
  lines.push('')
  lines.push(
    'Generated by `tools/spec-coverage` from `openspec/specs/**/spec.md` and the machine-readable',
    'results of the three gated test layers. Do not edit by hand — the next run overwrites it.'
  )
  lines.push('')
  lines.push(`Generated: ${generatedAt}`)
  lines.push('')
  lines.push(
    `**${analysis.covered} of ${analysis.total} specified scenarios covered ` +
      `(${analysis.percentage.toFixed(1)}%).**`
  )
  lines.push('')
  lines.push(
    'Scenario coverage is tracked separately from line coverage and does not gate the run; it says',
    'what is left to test, not how thoroughly the tested code is exercised.'
  )
  lines.push('')

  lines.push('## Layers in this report')
  lines.push('')
  lines.push('| Layer | Result file | Tests | Claiming a scenario |')
  lines.push('|---|---|---|---|')
  for (const layer of layers) {
    const claiming = layer.tests.filter((t) => t.scenarioIds.length > 0).length
    lines.push(
      `| ${LAYER_LABELS[layer.layer]} | ${layer.ran ? `\`${layer.path}\`` : '_not run_'} ` +
        `| ${layer.ran ? layer.tests.length : '—'} | ${layer.ran ? claiming : '—'} |`
    )
  }
  lines.push('')
  if (layers.some((l) => !l.ran)) {
    lines.push(
      '> A layer shown as _not run_ contributed nothing to this report. Its scenarios appear as',
      '> uncovered, which is a gap in the report rather than a gap in the tests.'
    )
    lines.push('')
  }

  if (analysis.unknownClaims.length > 0) {
    lines.push('## Stale claims')
    lines.push('')
    lines.push('These tests claim identifiers that match no scenario in the specs.')
    lines.push('')
    lines.push('| Claimed identifier | Layer | Test |')
    lines.push('|---|---|---|')
    for (const claim of analysis.unknownClaims) {
      lines.push(`| \`${claim.scenarioId}\` | ${LAYER_LABELS[claim.layer]} | ${claim.testName} |`)
    }
    lines.push('')
  }

  lines.push('## Per capability')
  lines.push('')
  lines.push('| Capability | Covered | Total | % |')
  lines.push('|---|---:|---:|---:|')
  for (const capability of analysis.perCapability) {
    lines.push(
      `| [${capability.capability}](#${capability.capability}) | ${capability.covered} ` +
        `| ${capability.total} | ${capability.percentage.toFixed(0)}% |`
    )
  }
  lines.push(
    `| **total** | **${analysis.covered}** | **${analysis.total}** ` +
      `| **${analysis.percentage.toFixed(1)}%** |`
  )
  lines.push('')

  for (const capability of analysis.perCapability) {
    lines.push(`## ${capability.capability}`)
    lines.push('')
    lines.push(
      `${capability.covered} of ${capability.total} scenarios covered ` +
        `(${capability.percentage.toFixed(0)}%).`
    )
    lines.push('')

    const covered = capability.scenarios.filter((s) => s.covered)
    const notPassing = capability.scenarios.filter((s) => s.claimedButNotPassing)
    const uncovered = capability.scenarios.filter((s) => !s.covered && !s.claimedButNotPassing)

    if (covered.length > 0) {
      lines.push('### Covered')
      lines.push('')
      lines.push('| Scenario | Layers | Tests |')
      lines.push('|---|---|---|')
      for (const scenario of covered) {
        const tests = scenario.passing.map((c) => `${LAYER_LABELS[c.layer]}: ${c.testName}`).join('<br>')
        lines.push(`| \`${scenario.slug}\` — ${scenario.name} | ${scenario.layers.join(', ')} | ${tests} |`)
      }
      lines.push('')
    }

    if (notPassing.length > 0) {
      lines.push('### Claimed by a test that did not pass')
      lines.push('')
      for (const scenario of notPassing) {
        const tests = scenario.claims
          .map((c) => `${LAYER_LABELS[c.layer]}: ${c.testName} (${c.status})`)
          .join('; ')
        lines.push(`- \`${scenario.id}\` — ${scenario.name} — ${tests}`)
      }
      lines.push('')
    }

    if (uncovered.length > 0) {
      lines.push('### Uncovered')
      lines.push('')
      for (const scenario of uncovered) {
        lines.push(`- \`${scenario.id}\` — **${scenario.requirement}** → ${scenario.name}`)
      }
      lines.push('')
    }
  }

  return lines.join('\n') + '\n'
}

export function renderConsole(analysis, layers, reportPath) {
  const lines = []
  const width = Math.max(...analysis.perCapability.map((c) => c.capability.length), 10)

  lines.push('Scenario coverage')
  lines.push('-'.repeat(60))
  for (const capability of analysis.perCapability) {
    const bar = capability.covered === capability.total && capability.total > 0 ? 'OK ' : '   '
    lines.push(
      `  ${bar}${capability.capability.padEnd(width)}  ` +
        `${String(capability.covered).padStart(3)}/${String(capability.total).padEnd(3)} ` +
        `${capability.percentage.toFixed(0).padStart(3)}%`
    )
  }
  lines.push('-'.repeat(60))
  lines.push(
    `  ${'total'.padEnd(width + 3)}  ${String(analysis.covered).padStart(3)}/` +
      `${String(analysis.total).padEnd(3)} ${analysis.percentage.toFixed(1).padStart(5)}%`
  )
  lines.push('')

  const notRun = layers.filter((l) => !l.ran).map((l) => LAYER_LABELS[l.layer])
  if (notRun.length > 0) {
    lines.push(`  Layers not included (no result file): ${notRun.join(', ')}`)
  }
  for (const layer of layers.filter((l) => l.error)) {
    lines.push(`  Could not read ${LAYER_LABELS[layer.layer]} results: ${layer.error}`)
  }

  if (analysis.unknownClaims.length > 0) {
    lines.push('')
    lines.push(`  ${analysis.unknownClaims.length} stale scenario claim(s):`)
    for (const claim of analysis.unknownClaims) {
      lines.push(`    ${claim.scenarioId}`)
      lines.push(`      claimed by ${LAYER_LABELS[claim.layer]} test: ${claim.testName}`)
    }
    lines.push('')
    lines.push('  No scenario in openspec/specs matches those identifiers. Either the claim is')
    lines.push('  misspelled, or the scenario was renamed or removed in the specs.')
  }

  lines.push('')
  lines.push(`  Report: ${reportPath}`)

  return lines.join('\n')
}
